const CHANGE_OPENID = 'CHANGE_OPENID'   //改变openid
const CHANGE_ACTIVITYID = 'CHANGE_ACTIVITYID'   //改变activity_id的值
const CHANGE_COUPON_CODE = 'CHANGE_COUPON_CODE' //改变卡券的兑换码
const CHANGE_SHOW_RULES = 'CHANGE_SHOW_RULES'   //改变规则弹窗